# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0a64d8370a0d5876d796e83d78580bf79a98ffe01c9bd62618130e668656a47d8cb7af60e8af865dd5a2fe0a653e94c6229b70ccea2d29678c799b6cdf9ba73

test:
  secret_key_base: 5479d235ab890ca69d9d8721a93da6a6edf42c94418620fe1ce3abf05571e22524e31082122777f6aa37f2c2d26f9aee989ad6fcacc4c49ac630706e5cc80383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
